common/urls.py
# common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('', views.home, name='home'),
]

kt_coaching_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from captcha import urls as captcha_urls
from rpg import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("common.urls")),
    path("rpg/", include("rpg.urls")),
    path("account/", include("account.urls")),
    path("mypage/", include("mypage.urls")),
    path("analysis/", include("analysis.urls")),
    path("community/", include("community.urls")),
    path("admin_page/", include("admin_page.urls")),
    path('captcha/', include(captcha_urls)),
    path('grow_practice/', include('grow_practice.urls')),
]

mypage/urls.py
from django.urls import path
from . import views
from rpg import views as rpg_views
app_name = 'mypage'

urlpatterns = [
    path('', views.mypage_view, name='mypage_view'),
    path('myp_info/', views.myp_info, name='myp_info'),
    path('myp_survey/', views.myp_survey, name='myp_survey'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('share_persona/<int:persona_id>/', views.share_persona, name='share_persona'),
    path('stop_sharing/<int:persona_id>/', views.stop_sharing, name='stop_sharing'),
    path('rating_list/<int:persona_id>/', views.rating_list, name='rating_list'),
    path('graph_draw/', views.graph_draw, name='graph_draw'),
    path('popup/', views.popup, name='popup'),
    # path('password_check/', views.password_check, name='password_check')
]

rpg/urls.py
# rpg/urls.py
from django.urls import path, include
from .views import rpg, persona
from . import views
from analysis import views as a_views

app_name = "rpg"
urlpatterns = [
    path('rpg_start/', views.rpg, name='rpg_start'),
    path('stt/', views.stt, name="stt"),
    path('loading/', views.loading, name="loading"),
    path('', views.persona, name='persona'),
]

rpg/models.py
from django.db import models
from account.models import Account
 
class Persona(models.Model):
    topic_label   = models.CharField(max_length=64)
    department    = models.CharField(max_length=45)
    rank          = models.CharField(max_length=45)
    age           = models.IntegerField()
    gender        = models.CharField(max_length=4)
    voice         = models.CharField(max_length=45)
    career        = models.IntegerField()
    nickname      = models.ForeignKey(Account, to_field="nickname", on_delete=models.CASCADE)
    shared        = models.BooleanField(default=False)
    is_working    = models.BooleanField(default=True)
    
class Message(models.Model):
    name        = models.CharField(max_length=45)
    persona     = models.ForeignKey(Persona, on_delete=models.CASCADE)
    content     = models.TextField()
    send_date   = models.DateTimeField(auto_now_add=True)
    voice_url   = models.TextField()
    csv_url     = models.TextField()
    grow_url    = models.TextField()
    
    class Meta:
        ordering    =   ("send_date",)

    
    

rpg/forms.py
# rpg/forms.py
from django import forms
from django.contrib.auth import authenticate
from rpg.models import Persona
 
class RegisterPersona(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ('topic_label', 'department', 'rank', 'age', 'gender', 'career', 'voice',)

rpg/views.py
# rpg/views.py

# 일반 파이썬 패키지
import numpy as np
import pandas as pd
import os
import pickle, joblib

# Django
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.db import transaction
import openai, json, requests
from django.conf import settings
from django.core.files.storage import FileSystemStorage


# DB 관련
from .forms import RegisterPersona
from .models import Persona, Message
from account.models import Account

# Goolge stt/tts
from google.cloud import speech, texttospeech
from google.cloud import speech_v1p1beta1 as speech
from google.oauth2 import service_account

# 인코딩 관련
import scipy.io.wavfile as wav
from scipy.signal import resample
from scipy.io.wavfile import write
import wave
import base64
from io import BytesIO
import subprocess

# 전처리 및 AI 분류 관련
from keras.models import load_model
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sentence_transformers import SentenceTransformer
import librosa
import random
import re
#----------------------------------------------------------------------------------------------------------------------#
# 0. 필요 install 목록
# pip install soundfile
# pip install sounddevice
# pip install --upgrade google-api-python-client
# pip install google-cloud-speech
# pip install google-cloud-texttospeech
# pip install openai
# pip install sentence-transformers
# pip install librosa
# conda install -c conda-forge ffmpeg
# pip install captcha
# pip install django-simple-captcha
# 구글 stt 관련 추가로 설정해야함.
#----------------------------------------------------------------------------------------------------------------------#

# to. 18조
# request 매개변수를 갖는 함수는 rpg.js와 urls.py를 참고해서 이해하면 더 쉽습니다. -from 충영


#----------------------------------------------------------------------------------------------------------------------#
# 1. 네이버 번역 관련
#----------------------------------------------------------------------------------------------------------------------#

# OpenAI의 api_key 설정
openai.api_key = 'openai.api_key 입력'


def translate(text):
    # 네이버 클라우드 플랫폼에서 발급받은 ID와 Secret을 입력
    client_id = '번역을 위한 API ID'
    client_secret = '번역을 위한 네이버 클라우드 API 암호'
    # 파파고 번역 API를 사용하기 위한 설정
    # 한국어(ko)를 영어(en)로 번역하도록 설정
    data = {'source':'ko', 'target':'en', 'text': text}
    url = "https://naveropenapi.apigw.ntruss.com/nmt/v1/translation"
    
    # 네이버 API를 사용하기 위해 요청 헤더에 ID와 Secret을 추가
    headers = {
        "X-NCP-APIGW-API-KEY-ID": client_id,
        "X-NCP-APIGW-API-KEY": client_secret
    }
    
    # 파파고 API에 POST 요청을 보내고 응답을 받기
    response = requests.post(url, headers=headers, data=data)
    
    # 응답을 JSON 형식으로 파싱하고 번역된 텍스트를 반환
    res = json.loads(response.text)
    return res['message']['result']['translatedText']

def retranslate(text):
    # 네이버 클라우드 플랫폼에서 발급받은 ID와 Secret을 입력
    client_id = '번역을 위한 API ID'
    client_secret = '번역을 위한 네이버 클라우드 API 암호'
    
    # 파파고 번역 API를 사용하기 위한 설정
    # 영어(en)를 한국어(ko)로 번역하도록 설정합니다. 공손한 어투를 사용하도록 설정
    data = {'source':'en', 'target':'ko', 'text': text, 'honorific':'true'}
    url = "https://naveropenapi.apigw.ntruss.com/nmt/v1/translation"
    
    # 네이버 API를 사용하기 위해 요청 헤더에 ID와 Secret을 추가
    headers = {
        "X-NCP-APIGW-API-KEY-ID": client_id,
        "X-NCP-APIGW-API-KEY": client_secret
    }
    
    # 파파고 API에 POST 요청을 보내고 응답을 받기
    response = requests.post(url, headers=headers, data=data)
    
    # 응답을 JSON 형식으로 파싱하고 번역된 텍스트를 반환
    res = json.loads(response.text)
    return res['message']['result']['translatedText']

#----------------------------------------------------------------------------------------------------------------------#
# 2. 패르소나 생성
#----------------------------------------------------------------------------------------------------------------------#

def persona(request):
    # 로그인 안했으면 로그인 하러 가는걸로 ^^
    if not request.user.is_authenticated :
        return redirect('account:login')
    
    # POST라면 입력한 내용을 form을 이용하여 데이터베이스에 저장
    if request.method == "POST":
        form = RegisterPersona(request.POST)
        # 유효성 검사
        if form.is_valid():
            form.nickname = request.user.nickname
            persona = form.save(commit=False)
            persona.nickname = Account.objects.get(nickname=request.user.nickname)
            persona.save()
            request.session['visited_persona'] = True
            request.session["persona_set"].append({
                                    "role" : "user",
                                    "content" : "당신의 이름은 '홍길동'입니다. 당신은 {0}세인 {1} {2}직군의 {3}입니다. 당신은 {4}인 직원입니다. 당신은 3문장 이하로 대답합니다.".format(
                                        form.cleaned_data['age'], # 0 나이 - gpt
                                        form.cleaned_data['department'], # 2 직군 - gpt
                                        form.cleaned_data['rank'], # 3 직급 - gpt
                                        form.cleaned_data['gender'], # 1 성별 - gpt
                                        form.cleaned_data['topic_label'], # 4 상황 - gpt
                                        )
                                    })
            request.session["persona_set"].append({
                                    "role" : "assistant", 
                                    "content" : "네! 이제부터 제 이름은 '홍길동'이고 저는 지금부터 {0}세인 {1} {2}직군의 {3}이며 {4}인 코칭받는 직원입니다.".format(
                                        form.cleaned_data['age'], # 0 나이 - gpt
                                        form.cleaned_data['gender'], # 1 성별 - gpt
                                        form.cleaned_data['department'], # 2 직군 - gpt
                                        form.cleaned_data['rank'], # 3 직급 - gpt
                                        form.cleaned_data['topic_label'], # 4 상황 - gpt
                                        )
                                    })
            # 프롬프트 연구결과 챗지피티의 첫 답장을 선 입력한 경우 더 제대로 인식한 것으로 판단해 더 오래 제대로 역할을 유지함
            persona_id = Persona.objects.filter(nickname=request.user.nickname).last()
            request.session.get("persona_id").append({
                "id" : f"{persona_id.id}"
            })
            request.session["voice"] = request.POST.get('voice') # 챗봇의 목소리 형태를 저장할 세션 변수
            request.session["count"] = 0 # 대화 주고받는 순서 저장할 세션 변수
            request.session['scores'] = []
            request.session['topic'] = "{0}의 {1} 홍길동 {2}({3}세/{4}년차/{5})".format(
                                        form.cleaned_data['topic_label'], # 0 상황 - gpt
                                        form.cleaned_data['department'], # 1 직군 - gpt
                                        form.cleaned_data['rank'], # 2 직급 - gpt
                                        form.cleaned_data['age'], # 3 나이 - gpt
                                        form.cleaned_data['career'], # 4 경력 - gpt
                                        form.cleaned_data['gender'], # 5 성별 - gpt
                                        )
            request.session['age'] = form.cleaned_data['age']
            request.session['gender'] = form.cleaned_data['gender']
            request.session['grow_count'] = [0,0,0,0,0]
            request.session['token_limit_prevention'] = 0
            return redirect("rpg:rpg_start")
    else : # GET 방식인 경우
        # 폼 생성
        form = RegisterPersona(request.POST or None)
        # 페르소나 세션 생성
        request.session["persona_id"] = []
        request.session["persona_set"] = []
        return render(request, 'rpg/persona.html', {"form": form})

#----------------------------------------------------------------------------------------------------#
# 3. 롤플레잉 실행 과정 
#----------------------------------------------------------------------------------------------------#

def convert_webm_to_wav(input_file, output_file): #webm wav로 바꾸는 코드
    command = ['ffmpeg', '-i', input_file, output_file]
    subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def rpg(request):
    if len(request.session.get("persona_set")) == 0 :
        form = RegisterPersona(request.POST or None)
        return redirect("rpg:persona")
    
    base_dir = settings.BASE_DIR # 기본 디렉터리 경로 불러오기
    p_id = request.session.get("persona_id")[0]["id"] # 채팅방 id 불러오기
    
    
    # HTTP 요청이 POST 방식일 경우
    if request.method == "POST":
        request.session["analysis_qf"] = 1
        message = request.POST.get("message")# 사용자가 입력한 한국어 메세지
        
        #--------------PAPAGO API 이용하여 번역후 chatGPT보내고 싶을 경우-----------------#
        # 번역된 사용자 입력 메세지를 messages에 추가
        # request.session.get('messages').append({"role": "user", "content": translate(message) +'. '+ '당신은 ' + request.session['topic'] + '라는 것을 잊지마세요. 자기소개는 하지말고 3문장이내로 대답해주세요.'})

        #--------------PAPAGO API 사용 안한 버전------------------#
        # 번역 없이 messages에 추가
        request.session.get('messages').append({"role": "user", "content": message +'. '+ '당신은 '+ request.session['topic']+'이라는 것을 잊지마세요. 자기소개는 하지말고 3문장이내로 대답해주세요.'})
        count = request.session.get("count") # url 경로 저장을 위한 대화 카운트 설정
        user_voice_url = os.path.join(base_dir, 'rpg/static/voice/{0}_{1}.webm'.format(p_id, count))
        wav_voice_url = os.path.join(base_dir, 'rpg/static/voice/{0}_{1}.wav'.format(p_id, count))
        convert_webm_to_wav(user_voice_url, wav_voice_url)

        # ----------------------------------- AI 전처리 / AI prediction ------------------------------------#
        m_df = classification_model(message, wav_voice_url)
        m_df_url = os.path.join(base_dir, 'rpg/static/df_csv/{0}_{1}.csv'.format(p_id, count))
        m_df.to_csv(m_df_url, index=False)
        # --------------------------------- GROW_AI 전처리 / AI prediction ---------------------------------#
        
        grow_df = grow_model(message)
        grow_df_url = os.path.join(base_dir, 'rpg/static/df_grow/{0}_{1}.csv'.format(p_id, count))
        grow_df.to_csv(grow_df_url, index=False)
        grow_info = "ETC"

rpg/templates/rpg/loading.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'rpg/loading.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'rpg/loading.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

<!-- 로딩창 -->
<div class="analysis_loading">
    <div>AI 대화 분석을 통해 코칭 대화에서 코칭 리더십 요인을 분석하고 있습니다.</div>
    <img src="/static/img/loading.gif" alt="로딩이미지">
    <div>잠시만 기다려 주세요.</div>
</div>
{% endblock %}

rpg/templates/rpg/mypersona.html
<!-- Mypage 템플릿 (mypage.html) -->
{% extends "base.html" %}
{% block content %}
  <h1>마이 페이지</h1>

  <h2>나의 페르소나</h2>
  <ul>
    {% for persona in personas %}
    <li>
      페르소나 ID: {{ persona.pk }}, 닉네임: {{ persona.nickname }}
      {% if persona.shared %}
        <form action="{% url 'rpg:stop_sharing' persona.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit">공유 중지</button>
        </form>
      {% else %}
        <form action="{% url 'rpg:share_persona' persona.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit">공유하기</button>
        </form>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
{% endblock %}

rpg/templates/rpg/persona.html
{% extends "base.html" %}
{% load static %}

{% block header_color %}
    #ff0000  <!-- 홈 페이지에서는 헤더 색상을 빨간색으로 설정 -->
{% endblock %}

{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'persona/persona.css' %}">
<link rel="stylesheet" href="{% static 'header.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'persona/persona.js' %}" defer></script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script> <!-- IONICONS -->

<!-- 헤더 -->
<!-- <div class="commu_head_wrapper">
  <div class="commu_head_menu_wrapper" style="display: inline;">
      {% comment %} href는 아직 구현 안 됨 {% endcomment %}
      <a class="commu_head_menu"><ion-icon name="information-circle" class="commu_head_menu_icon"></ion-icon></a>
      <a href="{% url 'common:home' %}" class="commu_head_menu"><ion-icon name="exit-outline" class="commu_head_menu_icon"></ion-icon></a>
    </div>
</div>
-->

<!-- 사이드 바 -->
<!-- <div class="l-navbar" id="navbar">
  <nav class="nav">
    <div>
      <div class="nav__brand">
        <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
        <a href="#" class="nav__logo">KT coaching</a>
      </div>
      <div class="nav__btn">
        <button class="new_chat_btn">
          <ion-icon name="add-circle-outline"></ion-icon>
          <div>New Chat</div>
        </button>
      </div>
      <div class="nav__list">
        {% comment %} <a href="#" class="nav__link active">
            <ion-icon name="home-outline" class="nav__icon"></ion-icon>
            <span class="nav_name">New Chat</span>
        </a> {% endcomment %}
        <div href="#" class="nav__link collapse">
          <ion-icon name="chatbubbles-outline" class="nav__icon"></ion-icon>
          <span class="nav_name">2023.06.05</span>
            <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>

            <ul class="collapse__menu">
                <a href="#" class="collapse__sublink">코칭시뮬레이션2차</a>
                <a href="#" class="collapse__sublink">코칭시뮬레이션1차</a>
            </ul>
        </div>
      </div>
  </nav>
</div> --> 

  <!-- 페르소나 메인 -->
    <div class="con"></div>

    <div class="persona_wrapper">
      <div class="persona_wrapper_layout">
        <div class="persona_profile">
          <div class="persona_profile_box"> <!-- 프로필 박스 -->
            <img class="persona_profile_kt" src="/static/img/kt.png" alt="kt로고">
            <div class="persona_profile_name"> 홍길동 </div>
            <img class="persona_profile_char" id="persona_image" src="/static/img/default.png" alt="페르소나1">
          </div>
        </div>
        <div class="persona_setting">
          <div class="persona_setting_title">Make Your Persona</div>
          <div class="persona_setting_content">
            <script>
              function updatePersonaImage() {
                let age = document.getElementById("id_age").value;
                let gender = document.getElementById("gender").value;
                let imageElement = document.getElementById("persona_image");
            
                let ageGroup = null;
                let imageName = "";
            
                if (age >= 18 && age <= 29) {
                  ageGroup = "young";
                } else if (age >= 30 && age <= 39) {
                  ageGroup = "middle";
                } else if (age >= 40 && age <= 49) {
                  ageGroup = "senior";
                } else if (age >= 50 && age <= 59) {
                  ageGroup = "elder";
                } else if (age >= 60) {
                  ageGroup = "old";
                }
            
                if (gender === "남성" && ageGroup !== null) {
                  imageName = ageGroup + "_male";
                } else if (gender === "여성" && ageGroup !== null) {
                  imageName = ageGroup + "_female";
                } else {
                  imageName = "default";
                }
          
                imageElement.src = "/static/img/" + imageName + ".png";
                imageElement.alt = imageName;
              }
            </script>
            
            <form method="post">
              <!-- 폼 필드들 -->
              {% csrf_token %}
                {% if error_message %}
                <div class="error-message">
                  {{ error_message }}
                </div>
                {% endif %}
                <div class="persona_setting_topic">
                  <div class="persona_setting_content_topic">
                    <label class="persona_setting_content_topic_label" for="topic_label">대화 주제</label>
                    <select class="persona_select" name="topic_label" id="topic_label_select" required>
                      <option value="" selected>주제를 선택하세요.</option>
                      <option value="지금보다 성과를 더 늘리고 싶어하는 상황">성과에 대해 고민인 팀원과의 대화</option>
                      <option value="직장생활에 적응을 어려워하는 상황">직장생활이 익숙하지 않은 팀원과의 대화</option>
                      <option value="업무에 대한 자신감이 부족한 상황">업무에 대한 자신감이 부족한 팀원과의 대화</option>
                      <option value="개인적인 발전을 위해 진로를 고민하는 상황">개인적인 진로가 걱정인 팀원과의 대화</option>
                      <option value="직장 동료와 다툼이 있어 고민하는 상황">동료와 다툼이 있어 걱정인 팀원과의 대화</option>
                      <option value="개인적 성장이나 발전에 대한 얘기를 할 준비가 되어있는 상황">개인적 발전과 성장에 대한 주제로 팀원과의 대화</option>
                      <option value='직접입력'>직접 입력</option>
                    </select>
                    <input class="persona_input" type="text" name="topic_label" id="topic_label_input" placeholder='"~인 상황" 이라고 입력해 주세요.' style="display:none;" required>
                  </div>
                </div>
                <script>
                  // JavaScript 코드
                  const selectElement = document.getElementById('topic_label_select');
                  const inputElement = document.getElementById('topic_label_input');

                  // 대화 주제 변경 이벤트를 감지하여 처리
                  selectElement.addEventListener('change', function() {
                    if (selectElement.value === '직접입력') {
                      selectElement.style.display = 'none';  // Hide the select box
                      inputElement.style.display = 'inline-block';
                      inputElement.value = ""  // Show the input box
                    } else {
                      selectElement.style.display = 'inline-block';  // Show the select box
                      inputElement.style.display = 'none';
                      inputElement.value = selectElement.value;// Hide the input box
                    }
                  });
                </script>
              <hr class="persona_topic_line">

              <div class="persona_setting_select">
                <div class="persona_setting_select_first">
                  <div class="persona_select_wrapper">
                    <label for="department">직군</label>
                    <select class="persona_select" name="department" id="department" required>
                      <option value="">직군을 선택하세요.</option>
                      <option value="B2C직군">B2C</option>
                      <option value="네트워크직군">네트워크</option>
                      <option value="B2B직군">B2B</option>
                      <option value="R&D직군">R&D</option>
                      <option value="사업직군">사업부서</option>
                      <option value="지원직군">지원부서</option>
                    </select>
                  </div>

                  <div class="persona_select_wrapper">
                    <label for="rank">직급</label>
                    <select class="persona_select" name="rank" id="rank" required>
                      <option value="">직급을 선택하세요.</option>
                      <option value="사원">사원</option>
                      <option value="대리">대리</option>
                      <option value="과장">과장</option>
                      <option value="차장">차장</option>
                      <option value="부장">부장</option>
                    </select>
                  </div>
                </div>

                <div class="persona_setting_select_second">
                  <div class="persona_select_wrapper">
                    <label for="id_age">연령</label>
                    <input class="persona_select" min="18" max="100" type="number" name="age" id="id_age" oninput="updatePersonaImage()" required>
                  </div>

                  <div class="persona_select_wrapper">
                    <label for="gender">성별</label>
                    {% comment %} <input type="radio" name="gender" id="gender_male" value="M" required/>
                    <label for="gender_male">남성</label>
                    <input type="radio" name="gender" id="gender_female" value="F" required/>
                    <label for="gender_female">여성</label> {% endcomment %}
                    <select class="persona_select" name="gender" id="gender" oninput="updatePersonaImage()" required>
                      <option value="">성별</option>
                      <option value="남성">남성</option>
                      <option value="여성">여성</option>
                    </select>
                  </div>
                </div>
                
                <div class="persona_setting_select_third">
                  <div class="persona_select_wrapper">
                    <label for="voice">목소리</label>
                    <select class="persona_select" name="voice" id="voice" required>
                      <option value=""> 목소리를 선택하세요.</option>
                      <option value="ko-KR-Standard-D"> 밝은 남성 목소리</option>
                      <option value="ko-KR-Wavenet-C"> 차분한 남성 목소리</option>
                      <option value="ko-KR-Standard-C"> 부드러운 남성 목소리</option>
                      <option value="ko-KR-Neural2-A"> 밝은 여성 목소리</option>
                      <option value="ko-KR-Neural2-B"> 차분한 여성 목소리</option>
                      <option value="ko-KR-Wavenet-B"> 중년 여성 목소리</option>
                    </select>
                  </div>

                  <div class="persona_select_wrapper">
                    <label for="career">경력</label>
                    <input class="persona_select" min="1" max="50" type="number" name="career" id="career" required/>
                  </div>
                </div>
              </div>
              <button class="persona_setting_content_btn" type="submit">대화 시작하기▶</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}