common/urls.py
# common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('', views.home, name='home'),
]

community/urls.py
# community/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.commu_list, name='commu_list'),
    path("notice/", views.notice_list, name="notice_list"),
    path("notice/<int:pk>/", views.notice_detail, name="notice_detail"),
    path("notice/create/", views.notice_create, name="notice_create"),
    path('survey/', views.survey_list, name="survey_list"),
    path('survey/<int:survey_id>/', views.survey_detail, name='survey_detail'),
    path('notice/<int:notice_id>/delete/', views.delete_notice, name='delete_notice'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kt_coaching_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from captcha import urls as captcha_urls
from rpg import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("common.urls")),
    path("rpg/", include("rpg.urls")),
    path("account/", include("account.urls")),
    path("mypage/", include("mypage.urls")),
    path("analysis/", include("analysis.urls")),
    path("community/", include("community.urls")),
    path("admin_page/", include("admin_page.urls")),
    path('captcha/', include(captcha_urls)),
    path('grow_practice/', include('grow_practice.urls')),
]

rpg/urls.py
# rpg/urls.py
from django.urls import path, include
from .views import rpg, persona
from . import views
from analysis import views as a_views

app_name = "rpg"
urlpatterns = [
    path('rpg_start/', views.rpg, name='rpg_start'),
    path('stt/', views.stt, name="stt"),
    path('loading/', views.loading, name="loading"),
    path('', views.persona, name='persona'),
]

community/models.py
# community/models.py
from django.db import models
from rpg.models import Persona, Message
from account.models import Account
import os

class Notice(models.Model):
    title         = models.CharField(max_length=200, blank=False, null=False)
    content       = models.TextField(blank=True, null=True)
    created_at    = models.DateTimeField(auto_now_add=True)
    file          = models.FileField(upload_to="uploads/", null=True, blank=True)
    is_working    = models.BooleanField(default=True)
    
    def get_filename(self):
        return os.path.basename(self.file.name)
    
class Survey(models.Model):
    author        = models.ForeignKey(Account, to_field='nickname', on_delete=models.CASCADE)
    persona_id    = models.ForeignKey(Persona, on_delete=models.CASCADE)
    title         = models.CharField(max_length=100, blank=False, null=False)
    content       = models.TextField(blank=True, null=True)
    shared        = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

    def get_messages(self):
        return Message.objects.filter(persona=self.persona_id)

    class Meta:
        ordering = ("-id",)
        
class Rating(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    user_nickname = models.CharField(max_length=100)
    score_1 = models.IntegerField()
    score_2 = models.IntegerField()
    score_3 = models.IntegerField()
    score_4 = models.IntegerField()
    score_5 = models.IntegerField()
    score_6 = models.IntegerField()
    score_7 = models.IntegerField()
    score_8 = models.IntegerField()
    score_9 = models.IntegerField()
    score_10 = models.IntegerField()
    score_11 = models.IntegerField()
    score_12 = models.IntegerField()
    score_13 = models.IntegerField()
    score_14 = models.IntegerField()
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

community/forms.py
# community/forms.py
from django import forms
from .models import Notice, Rating

class NoticeForm(forms.ModelForm):
    file = forms.FileField(required=False)  # 파일 필드 추가

    class Meta:
        model = Notice
        fields = ('title', 'content', 'file')  # 파일 필드 추가
        
class RatingForm(forms.ModelForm):
    item = forms.CharField(max_length=100)
    value = forms.IntegerField()

    class Meta:
        model = Rating
        fields = [
            'item',
            'value',
            'score_1',
            'score_2',
            'score_3',
            'score_4',
            'score_5',
            'score_6',
            'score_7',
            'score_8',
            'score_9',
            'score_10',
            'score_11',
            'score_12',
            'score_13',
            'score_14',
        ]

community/views.py
# community/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import HttpResponseBadRequest, HttpResponse, Http404
import urllib.parse
import mimetypes
import os
from rpg.models import Message
from .models import Notice, Survey, Rating
from .forms import NoticeForm, RatingForm


def commu_list(request):
    return render(request, 'community/commu_list.html')

# Create your views here.
def notice_list(request):
    notices = Notice.objects.filter(is_working=True).order_by('-created_at')
    reversed(notices)
    return render(request, 'community/notice_list.html', {'notices': notices})

@login_required
def notice_create(request):
    if request.method == "POST":
        form = NoticeForm(request.POST)
        if form.is_valid():
            notice = form.save(commit=False)
            if "file" in request.FILES:
                notice.file = request.FILES["file"]
            notice.save()
            messages.success(request, "공지사항 작성 완료")
            return redirect("community:commu_list")
    elif request.method == "GET":
        if not request.user.is_superuser:
            error_message = "허가되지 않은 행동입니다."
            script = f'<script>alert("{error_message}"); window.location.href="{reverse("community:commu_list")}";</script>'
            return HttpResponseBadRequest(script)
        else:
            form = NoticeForm()

    return render(request, "community/notice_create.html", {"form": form})

def notice_detail(request, pk):
    notice = get_object_or_404(Notice, pk=pk)

    if request.method == "POST" and 'download' in request.POST:
        if notice.file:
            file_path = notice.file.path
            if os.path.exists(file_path):
                with open(file_path, 'rb') as file:
                    file_name = os.path.basename(file_path)
                    file_name_encoded = urllib.parse.quote(file_name.encode('utf-8'))
                    content_type, _ = mimetypes.guess_type(file_path)
                    response = HttpResponse(file.read(), content_type=content_type)
                    response['Content-Disposition'] = f'attachment; filename*=UTF-8\'\'{file_name_encoded}'
                    return response
            else:
                message = "파일이 없습니다."
                return render(request, "community/notice_detail.html", {"notice": notice, "message": message})

    return render(request, "community/notice_detail.html", {"notice": notice})

def survey_list(request):
    user = request.user.nickname
    surveys = Survey.objects.filter(shared=True).select_related('author')
    user_rated_surveys = Rating.objects.filter(user_nickname=user).values_list('survey', flat=True)

    context = {
        'surveys': surveys,
        'user_rated_surveys': user_rated_surveys,
    }

    return render(request, 'community/survey_list.html', context)


def survey_detail(request, survey_id):
    survey = Survey.objects.get(id=survey_id)
    messages = Message.objects.filter(persona=survey.persona_id)
    checklist = [
            '구체적인 성과목표를 다시금 인식시켰습니까?',
            '원하는 모습이 무엇인지 구체적이고 명확하게 그려보게 하였습니까?',
            '목표 달성이 스스로에게 어떤 의미가 있는지 생각하게 하였습니까?',
            '현재의 성과 추진 상황을 객관적으로 바라볼 수 있게 하였습니까?',
            '현재 어떤 일이 일어나고 있는지 인식하게 하였습니까?',
            '현재 어떤 도전과 문제가 있는지 파악하게 하였습니까?',
            '목표와 현재의 갭(Gap)을 확인하도록 하였습니까?',
            '성과목표 달성을 위한 발전적 대안을 모색하게 하였습니까?',
            '고정관념에서 벗어나 새로운 시각으로 보도록 하였습니까?',
            '발상 단계에서 아이디어를 평가하지 않았습니까?',
            '성과목표의 최종 달성을 위한 구성원의 실행의지를 다졌습니까?',
            '목표를 달성하기 위한 대안 중에서 실행할 것을 선택하도록 하였습니까?',
            '구체적으로 무엇을, 언제, 어떻게 할 것인지 명확히 하도록 하였습니까?',
            '격려하고 지지하며 신뢰를 표시하였습니까?'
        ]
    
    user_has_rated = Rating.objects.filter(survey=survey, user_nickname=request.user.nickname).exists()
    
    if user_has_rated:
        error_message = "이미 참여한 설문입니다."
        script = f'<script>alert("{error_message}"); window.location.href="{reverse("community:commu_list")}";</script>'
        return HttpResponseBadRequest(script)
    
    if request.method == 'POST':
        ratings = []
        rating = Rating(survey=survey, user_nickname=request.user.nickname)

        for i, item in enumerate(checklist):
            rating_value = int(request.POST.get(f'rating_{i}', 0))
            setattr(rating, f'score_{i + 1}', rating_value)
        
        # Handle the comment separately
        comment = request.POST.get('comment', '')
        rating.comment = comment

        ratings.append(rating)

        Rating.objects.bulk_create(ratings)
        return redirect('community:commu_list')
    
    context = {
        'survey': survey,
        'messages': messages,
        'checklist': checklist
    }
    return render(request, 'community/survey_detail.html', context)

@login_required
def delete_notice(request, notice_id):
    if request.method == 'POST':
        notice = Notice.objects.get(id=notice_id)
        notice.is_working = False
        notice.save()
        return redirect('community:commu_list')

community/templates/community/commu_list.html
{% extends "base.html" %}
{% comment %} 메인 {% endcomment %}

{% load static %}

{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/community/community.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static '/community/community.js' %}" defer></script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script> <!-- IONICONS -->

<!-- 헤더 -->
<!--<div class="commu_head_wrapper">
  <div class="commu_head_menu_wrapper" style="display: inline;">
      {% comment %} href는 아직 구현 안 됨 {% endcomment %}
      <a href="{% url 'community:commu_list' %}" class="commu_head_menu"><ion-icon name="information-circle" class="commu_head_menu_icon"></ion-icon></a>
      <a href="{% url 'common:home' %}" class="commu_head_menu"><ion-icon name="exit-outline" class="commu_head_menu_icon"></ion-icon></a>
  </div>
</div>-->

<!-- 사이드 바 -->
<div class="navbar" id="navbar">
  <nav class="nav">
    <div>
      <div class="nav__brand">
        <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
        {% comment %} <a href="{% url 'common:home' %}" class="nav__logo">KT coaching</a> {% endcomment %}
      </div>
      <div class="nav__list">
        <a href="#" class="nav__link active" onclick="loadContent('notice_list')">
          <ion-icon name="megaphone-outline" class="nav__icon" onclick="loadContent('notice_list')"></ion-icon>
          <span class="nav_name" onclick="loadContent('notice_list')">공지사항</span>
        </a>
        <a href="#" class="nav__link active" onclick="loadContent('survey_list')">
          <ion-icon name="receipt-outline" class="nav__icon" onclick="loadContent('survey_list')"></ion-icon>
          <span class="nav_name" onclick="loadContent('survey_list')">설문목록</span>
        </a>
    </div>
  </nav>
</div>

<!-- 메인 페이지 -->
<div class="row">
  {% comment %} <div class="col-md-3">
  </div> {% endcomment %}
  <div class="col-md-9">
    <!-- 오른쪽 내용 -->
    <div class="commu_content" id="content-container">
    <!-- 내용이 동적으로 로드될 영역 -->
    </div>
  </div>
</div>

 

<script>
  // 페이지 로드 시 기본 내용 표시
  window.onload = function() {
    loadContent('notice_list');
  };

 

  // 내용 로드 함수
  function loadContent(contentType) {
    var url;
    if (contentType === 'notice_list') {
      url = "{% url 'community:notice_list' %}";
    } else if (contentType === 'survey_list') {
      url = "{% url 'community:survey_list' %}";
    }

    // AJAX 요청을 통해 해당 페이지의 내용 로드
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.onreadystatechange = function() {
      if (xhr.readyState === XMLHttpRequest.DONE) {
        if (xhr.status === 200) {
          // 내용 로드 성공 시, 컨테이너에 내용 삽입
          document.getElementById('content-container').innerHTML = xhr.responseText;
        } else {
          // 내용 로드 실패 시, 에러 메시지 표시
          document.getElementById('content-container').innerHTML = '내용을 로드할 수 없습니다.';
        }
      }
    };
    xhr.send();
  }
</script>
{% endblock %}

community/templates/community/notice_create.html
{% extends "base.html" %}
{% comment %} 공지 작성 페이지 {% endcomment %}

{% load static %}
{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/community/notice.css' %}">
<link rel="stylesheet" href="{% static '/community/community.css' %}">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script> <!-- IONICONS -->

<!-- 헤더 -->
{% comment %} <div class="commu_head_wrapper">
    <div class="commu_head_menu_wrapper" style="display: inline;">
        <a href="{% url 'community:commu_list' %}" class="commu_head_menu"><ion-icon name="information-circle" class="commu_head_menu_icon"></ion-icon></a>
        <a href="{% url 'community:commu_list' %}" class="commu_head_menu"><ion-icon name="exit-outline" class="commu_head_menu_icon"></ion-icon></a>
    </div>
</div> {% endcomment %}

<!-- 메인 -->
<div class="notice_create_wrapper">
    <div class="notice_create_contain">
        <div class="notice_create_title">공지사항 작성</div>
        <button class="back_button" onclick="window.history.back();">&lt</button>
        <div class="notice_create_content">
            <div class="notice_create_table">
                <form method="POST" enctype="multipart/form-data">  <!-- enctype 속성 추가 -->
                    {% csrf_token %}
                    <table class="table" border="0" width="100%" height="400">
                        <tr><!-- 첫번째 줄 시작 -->
                            <td style="background-color:#EDEDED;"><label for="id_title">제목</label></td>
                            <td><input class="notice_create_input_title" style="border: none" type="text" name="title" id="id_title"></td>
                        </tr><!-- 첫번째 줄 끝 -->
                        <tr><!-- 두번째 줄 시작 -->
                            <td style="background-color:#EDEDED;"><label for="id_content">내용</label></td>
                            <td><textarea class="notice_create_input_content"cols="50" rows="20" style="border: none" name="content" id="id_content" cols="30" rows="10"></textarea></td>
                        </tr><!-- 두번째 줄 끝 -->
                        <tr><!-- 두번째 줄 시작 -->
                            <td style="background-color:#EDEDED;"><label for="id_file">첨부파일</label></td>
                            <td><input type="file" name="file" id="id_file"></td>
                        </tr><!-- 두번째 줄 끝 -->
                    </table>
                    <input class="notice_create_content_submit" type="submit" value="작성">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/notice_detail.html
{% extends 'base.html' %}
{% comment %} 공지사항 세부사항: 게시글 {% endcomment %}

{% load static %}
{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/community/notice.css' %}">
<link rel="stylesheet" href="{% static '/community/community.css' %}">
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script> <!-- IONICONS -->

<!-- 헤더 -->
{% comment %} <div class="commu_head_wrapper">
    <div class="commu_head_menu_wrapper" style="display: inline;">
        <a class="commu_head_menu"><ion-icon name="information-circle" class="commu_head_menu_icon"></ion-icon></a>
        <a href="{% url 'community:commu_list' %}" class="commu_head_menu"><ion-icon name="exit-outline" class="commu_head_menu_icon"></ion-icon></a>
      </div>
</div> {% endcomment %}

<!-- 메인 -->
<div class="notice_detail_wrapper">
    <div class="notice_detail_contain">
        <div class="notice_detail_title">공지사항</div>
        <button class="back_button" onclick="window.history.back();">&lt</button>
        <!-- 공지사항 상세 -->
        <div class="notice_detail_content">
            <table class="table" border="0" width="100%" height="500">
                <tr height="40">
                    <td style="background-color:#EDEDED;"><label for="id_title">제목</label></td>
                    <td><div class="notice_detail_content_title">{{ notice.title }}</div></td>
                </tr>
                <tr height="40">
                    <td style="background-color:#EDEDED;"><label for="id_content">작성일자</label></td>
                    <td><div class="notice_detail_content_date">{{ notice.created_at }}</div></td>
                </tr>
                <tr height="40">
                    <td style="background-color:#EDEDED;"><label for="id_file">첨부파일</label></td>
                    <td>
                        {% if notice.file %}
                        {% if message %}
                            <div class="alert alert-warning">{{ message }}</div>
                        {% else %}
                            <form method="POST">
                                {% csrf_token %}
                                {{ notice.get_filename }}
                                <button type="submit" name="download">다운로드</button>
                            </form>
                        {% endif %}
                        {% else %}
                            <div class="alert alert-info">파일이 없습니다.</div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td style="background-color:#EDEDED;"><label for="id_content">내용</label></td>
                    <td><div class="notice_detail_content_txt">{{ notice.content }}</div></td>
                </tr>
            </table>
        </div>
        
        {% if user.is_authenticated and user.is_superuser %}
        <form method="POST" action="{% url 'community:delete_notice' notice.id %}">
            {% csrf_token %}
            <button type="submit" class="delete_button">공지 삭제하기</button>
        </form>
        {% endif %}
        
        {% comment %} <a href="{% url 'community:commu_list' %}">목록</a> {% endcomment %}
    </div>
</div>
{% endblock %}

community/templates/community/notice_list.html
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/community/notice.css' %}">
{% comment %} 공지사항 항목 리스트 {% endcomment %}
<div class="notice_list_wrapper">
  <div class="notice_list_header">
    <div class="notice_list_header_title">공지사항</div>
      <!-- 공지사항 목록을 순회하며 출력합니다 -->
      {% if user.is_authenticated and user.is_superuser %}
          <a class="notice_writing" href="{% url 'community:notice_create' %}">공지사항 작성</a>
      {% endif %}
    </div>
  </div>
  <div class="notice_list_content">
    {% for notice in notices %}
    <div class="list_wrapper">
      <div class="list_create_title"><a class="list_create_title_link"href="{% url 'community:notice_detail' notice.pk %}">{{ notice.title }}</a></div>
      <div class="list_create_date">작성일: {{ notice.created_at }}</div>
    </div>
    <hr class="notice_list_hr">
    {% empty %}
    <div>등록된 공지사항이 없습니다.</div>
    {% endfor %}
  </div>
</div>

community/templates/community/survey_detail.html
{% extends "base.html" %}
{% comment %} 설문 세부사항: 게시글 {% endcomment %}
{% load static %}

{% block content %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/community/survey.css' %}">
<link rel="stylesheet" href="{% static '/community/community.css' %}">
{% comment %} <script src="{% static 'community/survey_detail.js' %}"></script> {% endcomment %}
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script> <!-- IONICONS -->


<!-- 헤더 -->
{% comment %} <div class="commu_head_wrapper">
    <div class="commu_head_menu_wrapper" style="display: inline;">
        <a class="commu_head_menu"><ion-icon name="information-circle" class="commu_head_menu_icon"></ion-icon></a>
        <a href="{% url 'community:commu_list' %}" class="commu_head_menu"><ion-icon name="exit-outline" class="commu_head_menu_icon"></ion-icon></a>
      </div>
  </div> {% endcomment %}

<!-- 메인 -->
<div class="survey_detail_wrapper">
    <button class="back_button" onclick="window.history.back();">&lt</button>
    <div class="survey_detail_contain">
        <div class="survey_detail_head_wrapper">
            <div class="survey_detail_head_title">
                설문 요청
            </div>
            <div class="survey_detail_head_content">
                <div>제목: {{ survey.title }}</div>
                <div>내용: {{ survey.content }}</div>
            </div>
        </div>
        
        <div class="survey_detail_content_wrapper">
            <div class="survey_detail_conversation_contain">
                <div class="survey_detail_conversation_title">{{ survey.author }} 님의 코칭 대화</div>
                <div class="survey_detail_conversation_wrapper">
                    {% comment %} {{ message.name }} {% endcomment %}
                    {% for message in messages %}
                        {% comment %} {% if forloop.counter|divisibleby:2 %} {% endcomment %}
                        {% if message.name == "홍길동" %}
                        <div class="survey_detail_conversation_list_member">
                            <img class="survey_detail_conversation_list_pic_member" src="/static/img/young_male.png">
                            <div class="survey_detail_conversation_list_txt_member">{{ message.content }}</div>
                        </div>
                        {% else %}
                        <div class="survey_detail_conversation_list_coach">
                            <img class="survey_detail_conversation_list_pic_coach" src="/static/img/default.png">
                            <div class="survey_detail_conversation_list_txt_coach">{{ message.content }}</div>
                        </div>
                        {% endif %}
                    {% endfor %}                </div>
            </div>
            <div class="survey_detail_checklist_contain">
                <div class="survey_detail_checklist_wrapper">
                    <h4>체크리스트</h4>
                    <form id="ratingForm" method="POST" action="{% url 'community:survey_detail' survey.id %}">
                        {% csrf_token %}
                        {% for item in checklist %}
                        <div class="survey_detail_checklist_item_wrapper">
                            {% with index=forloop.counter %}
                            <div class="survey_detail_checklist_item">{{index}}. {{ item }}</div>
                            <label><input type="radio" name="rating_{{ forloop.counter0 }}" value="1">매우 그렇지 않다</label>
                            <label><input type="radio" name="rating_{{ forloop.counter0 }}" value="2">그렇지 않다</label>
                            <label><input type="radio" name="rating_{{ forloop.counter0 }}" value="3">그렇다</label>
                            <label><input type="radio" name="rating_{{ forloop.counter0 }}" value="4">매우 그렇다</label>
                            {% endwith %}
                        </div>
                        <hr class="survey_detail_checklist_item_hr">
                        {% endfor %}
                        <div class="form-group">
                            <label for="comment">더 하고 싶은 말이 있다면 자유롭게 적어주세요</label>
                            <textarea name="comment" id="comment" class="form-control"></textarea>
                        </div>
                        <button class="survey_detail_submit_btn" type="submit">설문완료</button>
                    </form>
                </div>
            </div>
        </div>
    {% comment %} <a href="{% url 'community:commu_list' %}">목록</a> {% endcomment %}
    </div>
</div>

<script>
    document.getElementById("ratingForm").addEventListener("submit", function(event) {
        var checklist = document.getElementsByClassName("survey_detail_checklist_item_wrapper");
        var allChecked = true; // 모든 항목이 체크되었는지 확인하기 위한 변수
    
        for (var i = 0; i < checklist.length; i++) {
            var radios = checklist[i].querySelectorAll("input[type='radio']");
            var checked = false;
    
            for (var j = 0; j < radios.length; j++) {
                if (radios[j].checked) {
                    checked = true;
                    break;
                }
            }
    
            if (!checked) {
                allChecked = false;
                break;
            }
        }
    
        if (!allChecked) {
            event.preventDefault(); // 폼 제출 막기
            alert("모든 항목을 완성해주세요.");
        } else {
            alert("설문 제출이 정상적으로 완료되었습니다.");
        }
    });
</script>
{% endblock %}

community/templates/community/survey_list.html
{% comment %} 설문 항목 리스트 {% endcomment %}
{% load static %}
{% block content %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/community/survey.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script> <!-- IONICONS -->

<div class="survey_list_wrapper">
    <div class="survey_list_title">설문 목록</div>
    <div class="survey_list_content">
    {% for survey in surveys %}
        <div class="survey_list_content_top">
            <div class="survey_list_content_title"><a class="survey_list_content_title_link" href="{% url 'community:survey_detail' survey.id %}">{{ survey.title }}</a></div>
            <div class="survey_list_content_producer">{{ survey.author }}</div>
        </div>
        <div class="survey_list_content_bottom">
            <div class="survey_list_content_text">{{ survey.content }}</div>
            {% if survey.id in user_rated_surveys %}
            <div class="survey_list_content_complete">[참여완료]</div>
            {% endif %}
        </div>
    <hr class="survey_list_hr">
    {% empty %}
        <div>등록된 설문이 없습니다.</div>
    {% endfor %}
    </div>
</div>
{% endblock %}