admin_page/urls.py
# rpg/urls.py
from django.urls import path, include
from . import views

app_name = "admin_page"

urlpatterns = [
    path('persona_statistics', views.admin_persona, name='admin_persona'),
    path("", views.admin_user, name='admin_user'), 
]

common/urls.py
# common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('', views.home, name='home'),
]

kt_coaching_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from captcha import urls as captcha_urls
from rpg import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("common.urls")),
    path("rpg/", include("rpg.urls")),
    path("account/", include("account.urls")),
    path("mypage/", include("mypage.urls")),
    path("analysis/", include("analysis.urls")),
    path("community/", include("community.urls")),
    path("admin_page/", include("admin_page.urls")),
    path('captcha/', include(captcha_urls)),
    path('grow_practice/', include('grow_practice.urls')),
]

rpg/urls.py
# rpg/urls.py
from django.urls import path, include
from .views import rpg, persona
from . import views
from analysis import views as a_views

app_name = "rpg"
urlpatterns = [
    path('rpg_start/', views.rpg, name='rpg_start'),
    path('stt/', views.stt, name="stt"),
    path('loading/', views.loading, name="loading"),
    path('', views.persona, name='persona'),
]

admin_page/models.py
from django.db import models

# Create your models here.

admin_page/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.db.models import Count, Case, When, Value, CharField
from rpg.models import Persona
from account.models import Account, admin_info
import numpy as np
import pandas as pd
import os
import json
from django.db.models.functions import ExtractWeekDay, ExtractHour

def admin_persona(request):
    if not request.user.is_superuser:
        return redirect("common:home")
    # Rank 종류별 갯수
    rank_counts = list(Persona.objects.values('rank').annotate(rank_count=Count('rank')))

    # Department 종류별 갯수
    department_counts = list(Persona.objects.values('department').annotate(department_count=Count('department')))

    # 성별 종류별 갯수
    gender_counts = Persona.objects.values('gender').annotate(gender_count=Count('gender'))

    # 상황 종류별 갯수
    topic_label_counts = list(Persona.objects.values('topic_label').annotate(topic_label_count=Count('topic_label')))

    # 연차 종류별 갯수
    career_counts = Persona.objects.values('career').annotate(career_count=Count('career'))

    # 상황 종류별 갯수
    age_counts = (
        Persona.objects
        .annotate(age_group=Case(
            When(age__range=(20, 29), then=Value('20대')),
            When(age__range=(30, 39), then=Value('30대')),
            When(age__range=(40, 49), then=Value('40대')),
            When(age__range=(50, 59), then=Value('50대')),
            When(age__range=(60, 69), then=Value('60대')),
            
            # 추가적인 연령대 범위를 필요에 따라 추가해주세요
            default=Value('기타'),
            output_field=CharField(),
        ))
        .values('age_group')
        .annotate(age_group_count=Count('age_group'))
    )

    # Total counts
    total_ranks = sum([item['rank_count'] for item in rank_counts])

    # Calculate ratios
    for item in rank_counts:
        item['rank_ratio'] = item['rank_count'] / total_ranks * 100

    for item in department_counts:
        item['department_ratio'] = item['department_count'] / total_ranks * 100

    for item in gender_counts:
        item['gender_ratio'] = item['gender_count'] / total_ranks * 100

    for item in topic_label_counts:
        item['topic_label_ratio'] = item['topic_label_count'] / total_ranks * 100

    for item in career_counts:
        item['career_ratio'] = item['career_count'] / total_ranks * 100

    for item in age_counts:
        item['age_group_ratio'] = item['age_group_count'] / total_ranks * 100

    context = {
        'rank_counts': json.dumps(list(rank_counts)),
        'department_counts': json.dumps(list(department_counts)),
        'gender_counts': json.dumps(list(gender_counts)),
        'topic_label_counts': json.dumps(list(topic_label_counts)),
        'career_counts': json.dumps(list(career_counts)),
        'age_counts': json.dumps(list(age_counts)),
    }
    return render(request, "admin_page/admin_persona.html", context)


def admin_user(request):
    if not request.user.is_superuser:
        return redirect("common:home")
    
    #--------------------이용량 통계------------------------------#
    weekday_mapping = {
        0: '토요일',
        1: '일요일',
        2: '월요일',
        3: '화요일',
        4: '수요일',
        5: '목요일',
        6: '금요일',
    }
    
    login_counts_by_weekday = admin_info.objects.annotate(weekday=ExtractWeekDay('login_date')).values('weekday').annotate(count=Count('id')).order_by('weekday')

    # 시간대별로 로그인 횟수를 추출
    login_counts_by_hour = admin_info.objects.annotate(hour=ExtractHour('login_date')).values('hour').annotate(count=Count('id')).order_by('hour')

    # 요일별 로그인 횟수를 저장할 리스트 변수
    weekday_counts = [0] * 7  # 0부터 6까지의 인덱스를 가진 리스트

    # 시간대별 로그인 횟수를 저장할 리스트 변수
    hour_counts = [0] * 24  # 0부터 23까지의 인덱스를 가진 리스트

    # for i in range(len(weekday_counts)):
    #     weekday_counts[i] = { "weekday" : weekday_mapping[i], 'value' : weekday_counts[i]}
    
    # 요일별 로그인 횟수 추출 결과를 리스트 변수에 저장
    for entry in login_counts_by_weekday:
        weekday_counts[entry['weekday']] = entry['count']
    for i in range(len(weekday_counts)):
        if i==0:
            weekday_counts[i] = { 'weekday' : '토' , "value" : weekday_counts[i]}
        elif i==1:
            weekday_counts[i] = { 'weekday' : '일' , "value" : weekday_counts[i]}
        elif i==2:
            weekday_counts[i] = { 'weekday' : '월' , "value" : weekday_counts[i]}    
        elif i==3:
            weekday_counts[i] = { 'weekday' : '화' , "value" : weekday_counts[i]}    
        elif i==4:
            weekday_counts[i] = { 'weekday' : '수' , "value" : weekday_counts[i]}    
        elif i==5:
            weekday_counts[i] = { 'weekday' : '목' , "value" : weekday_counts[i]}    
        elif i==6:
            weekday_counts[i] = { 'weekday' : '금' , "value" : weekday_counts[i]}    
            
            
    
    # 시간대별 로그인 횟수 추출 결과를 리스트 변수에 저장
    for entry in login_counts_by_hour:
        hour_counts[entry['hour']] = entry['count']
    for i in range(len(hour_counts)):
        hour_counts[i] = { 'time' : i , "vlaue_hour" : hour_counts[i]}
        
    #--------------------------분석결과 통계--------------------------#
    
    
    
    context = {
        'weekday_counts': json.dumps(list(weekday_counts),ensure_ascii=False),
        'hour_counts': json.dumps(list(hour_counts)),
    }
    return render(request, "admin_page/admin_page.html", context)

admin_page/templates/admin_page/admin_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0/dist/chart.min.js"></script>
  <script src="{% static '/admin_page/admin_user.js' %}" defer></script>
  <link rel="stylesheet" href="{% static 'admin_page/admin_user.css' %}">
  <link rel="icon" type="image/x-icon" sizes="16x16" href="/static/image/kt_favicon.png">
  <title>K-Training</title>
</head>

<body>
    <div class="sidebar">
        <a href="{% url 'common:home' %}" class="kt-coaching">K-Training</a>
        <div class="separator"></div>
        <div class="statistics">통계<span class="arrow">▼</span></div>
        <div class= "inside-info">
            <a href="{% url 'admin_page:admin_user' %}" id="visitors">사용자</a>
            <a href="{% url 'admin_page:admin_persona' %}" id="member-ratio">페르소나</a>
        </div>
    </div>
    <div class="main-section">
        <div class="main-top">
            <div class="main-top-text">
                사용자 통계
            </div>
        </div>   
        <div class="main-content">
           <div class="main-graph-box1">
                <div class="graph1-title">요일별 이용 현황</div>
                <div class="graph1">
                    <canvas id="weekday_Chart" style="height: 100%; width: 100%;"></canvas>
                </div>
                <script id="weekday_chart_data" type="application/json">
                    {{ weekday_counts | safe }}
                </script>
            </div>
            <br><br>
            <div class="main-graph-box2">
                <div class="graph1-title">시간대 별 이용 현황</div>
                <div class="graph2">
                    <canvas id="hour_Chart" style="height: 100%; width: 100%;"></canvas>
                </div>
                <script id="hour_chart_data" type="application/json">
                    {{ hour_counts | safe }}
                </script>
            </div>
        </div>
    </div>  
</body>
</html>

admin_page/templates/admin_page/admin_persona.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0/dist/chart.min.js"></script>
  <script src="{% static 'admin_page/admin_persona.js' %}" defer></script>
  <link rel="stylesheet" href="{% static 'admin_page/admin_persona.css' %}">
  <link rel="icon" type="image/x-icon" sizes="16x16" href="/static/image/kt_favicon.png">
  <title>K-Training</title>
</head>

<body>
    <div class="sidebar">
        <a href="{% url 'common:home' %}" class="kt-coaching">K-Training</a>
        <div class="separator"></div>
        <div class="statistics">통계<span class="arrow">▼</span></div>
        <div class= "inside-info">
            <a href="{% url 'admin_page:admin_user' %}" id="visitors">사용자</a>
            <a href="{% url 'admin_page:admin_persona' %}" id="member-ratio">페르소나</a>
        </div>
    </div>
    <div class="main-section">
        <div class="main-top">
            <div class="main-top-text">
                페르소나 통계
            </div>
        </div>   
        <div class="main-content">
            <div class="main-graph-box">
                <div class="main-graph-box1">
                    <div class="graph1-title">선택한 성별</div>
                    <div class="graph1">
                        <canvas id="gender_Chart"style="height: 100%; width: 100%;"></canvas>
                    </div>
                    <script id="gender_counts" type="application/json">
                        {{ gender_counts | safe }}
                    </script>
                </div>
                <div class="main-graph-box2">
                    <div class="graph1-title">선택한 연령대</div>
                    <div class="graph2">
                        <canvas id="age_Chart"style="height: 100%; width: 100%;"></canvas>
                    </div>
                    <script id="age_counts" type="application/json">
                        {{ age_counts | safe }}
                    </script>
                </div>
            </div>
            <div class="sub-graph-box">
                <div class="main-sub-graph-box1">
                    <div class="graph2-title">선택한 직군</div>
                    <div class="graph3">
                        <canvas id="department_Chart" style="height: 100%; width: 100%;"></canvas>
                    </div>
                    <script id="department_counts" type="application/json">
                        {{ department_counts | safe }}
                    </script>
                </div>
                <div class="main-sub-graph-box2">
                    <div class="graph3-title">선택한 직급</div>
                    <div class="graph4">
                        <canvas id="rank_Chart" style="height: 100%; width: 100%;"></canvas>
                    </div>
                    <script id="rank_counts" type="application/json">
                        {{ rank_counts | safe }}
                    </script>
                </div>
            </div>
        </div>
    </div>  
</body>
</html>


{% comment %} <!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Admin Page</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0/dist/chart.min.js"></script>
    <script src="{% static 'admin_page/admin_persona.js' %}" defer></script>
    <link rel="stylesheet" href="{% static '/admin_page/admin_persona.css' %}">
</head> {% endcomment %}

{% comment %} <body>
    <h1>Admin Page</h1>

    <div class="gender_graph">
        <canvas id="gender_Chart"></canvas>
    </div>
    <script id="gender_counts" type="application/json">
        {{ gender_counts | safe }}
    </script>

    <div class="age_graph">
        <canvas id="age_Chart"></canvas>
    </div>
    <script id="age_counts" type="application/json">
        {{ age_counts | safe }}
    </script>

    <div class="rank_graph">
        <canvas id="rank_Chart"></canvas>
    </div>
    <script id="rank_counts" type="application/json">
        {{ rank_counts | safe }}
    </script>
    
    <div class="department_graph">
        <canvas id="department_Chart"></canvas>
    </div>
    <script id="department_counts" type="application/json">
        {{ department_counts | safe }}
    </script>
    
    <a class="go_page"href="{% url 'admin_page:admin_user' %}">페르소나 통계 페이지로 가기</a>
</body>
</html> {% endcomment %}

admin_page/templates/admin_page/admin_user.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <style>
    body, html {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }

    .sidebar {
      position: fixed;
      width: 250px;
      min-height: 100vh;
      background-color: #002C4D;
      padding: 0;
      margin: 0;
      top: 0;
    }
    .sidebar a {
      display: block;
      color: white;
      text-decoration: none;
      padding: 8px 16px;
    }

    .separator {
      background-color: white;
      height: 1px;
      width: 80%;
      margin: 18px 0;
      margin-left: 20px;
    }

    .kt-coaching {
      font-size: 28px;
      font-weight: bold;
      margin-top: 15px;
      margin-left: 20px;
    }

    .kt-coaching:hover {
        color: #4C92C7;
    }

    .inside-info {
        margin-left: 19px;
        font-size: 14px;
    }

    .inside-info:hover {
        color: #4C92C7;
    }

    .main-top {
        position: fixed;
        width: calc(100% - 250px); 
        height: 85px;
        background-color: #002C4D;
        padding: 0;
        margin: 0;
        top: 0;
        right: 0;
    }

    .main-top-text {
        font-size: 28px;
        font-weight: 500;
        color: white;
        margin-top: 20px;
        margin-left: 20px;
    }

    .main-section {
        background-color: lightgray;
    }

    .main-content {
        margin-top: 85px;
        margin-left: 270px;
        padding: 10px;
        width: calc(100% - 260px - 17px); 
        height: 635px;
        box-sizing: border-box;
        background-color: lightgray; 
    }

    .main-graph-box {
        margin-top: 10px;
        margin-bottom: 15px;
        height: 300px;
        display: flex;
        flex-direction: column;
        justify-content: center; /* 변경된 부분 */
    }

    .sub-graph-box {
        margin-top: 10px;
        margin-bottom: 15px;
        height: 300px;
        display: flex;
        flex-direction: row;
        justify-content: center; /* 변경된 부분 */
    }

    .graph1-title, .graph2-title, .graph3-title {
        margin-left: 12px;
        background-color: lightgray;
    }

    .graph1-title {
        padding: 5px;
        left: 13px;
        font-size: 20px;
        font-weight: bold;
        width: 30%;
        height: 25px;
    }

    .graph2-title{
        padding: 5px;
        font-size: 20px;
        font-weight: bold;
        width: 50%;
        height: 25px;
    }

    .graph3-title{
        padding: 5px;
        font-size: 20px;
        font-weight: bold;
        width: 50%;
        height: 25px;
    }

    .graph1, .graph2, .graph3 {
        background-color: #ffff;
        border-radius: 5px;
        margin: 10px;
    }

    .graph1 {
        width: 90%;
        height: 250px;
    }

    .graph2, .graph3 {
        position: relative;
        width: 80%;
        height: 235px;
    }


    .main-sub-graph-box1 {
        display: flex;
        flex-direction: column;
        justify-content: flex-start; /* 변경된 부분 */
        width: 50%; /* 변경된 부분 */
        height: 290px
    }

    .main-sub-graph-box2 {
        display: flex;
        flex-direction: column;
        justify-content: flex-start; /* 변경된 부분 */
        width: 50%; /* 변경된 부분 */
        height: 290px
    }

    .arrow {
      float: right;
      font-size: 15px;
      margin-top: 5px;
      margin-left: 150px;
    }

    .statistics {
        display: inline-block;
        font-size: 18px;
        font-weight: bold;
        color: white;
        text-decoration: none;
        padding: 8px 16px;
    }

  </style>

  <!-- Add jQuery to the project -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% comment %} <script>
    // Add jQuery function to handle the click events
    $(document).ready(function() {
      $('#statistics').click(function() {
        // 슬라이드 효과를 사용하여 하위 메뉴를 추가/삭제
        $('.inside-info').slideToggle();
      });
    });
  </script> {% endcomment %}
</head>

<body>
    <div class="sidebar">
        <a href="{% url 'admin_page:admin_page' %}" class="kt-coaching">K-Training</a>
        <div class="separator"></div>
        <div class="statistics">통계<span class="arrow">▼</span></div>
        <div class= "inside-info">
            <a href="{% url 'admin_page:admin_user' %}" id="visitors">사용자</a>
            <a href="{% url 'admin_page:admin_persona' %}" id="member-ratio">페르소나</a>
        </div>
    </div>
    <div class="main-section">
        <div class="main-top">
            <div class="main-top-text">
                사용자 관리
            </div>
        </div>   
        <div class="main-content">
            <div class="main-graph-box">
                <div class="graph1-title">이용자 실습결과 분석</div>
                <div class="graph1"></div>    
            </div>
            <div class="sub-graph-box">
                <div class="main-sub-graph-box1">
                    <div class="graph2-title">요일 별 서비스 이용 횟수</div>
                    <div class="graph2"></div>
                </div>
                <div class="main-sub-graph-box2">
                    <div class="graph3-title">시간대 별 서비스 이용 횟수</div>
                    <div class="graph3"></div>
                </div>
            </div>
        </div>    
    </div>  
</body>
</html>